[workspace]
name = "nextpnr"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
boost-cpp = "*"
cmake = ">=3.25"
cxx-compiler = "*"
eigen = "*"
git = "*"
just = "*"
ninja = "*"
python = ">=3.9"
qt6-main = ">=6,<7"
rattler-build = "==0.70.0"
xz = "*"

[pypi-dependencies]
apycula = "==0.32"

[feature.conda-package.dependencies]
cmake = ">=3.25"
just = "*"
python = ">=3.12,<3.13"
rattler-build = "==0.70.0"

[environments]
conda-package = { features = ["conda-package"], no-default-feature = true }
